global:
  smtp_smarthost: 'localhost:25'
  smtp_from: 'alertmanager@example.org'
  smtp_auth_username: 'alertmanager'
smtp_auth_password: 'password'
templates:
  - '/etc/alertmanager/template/*.tmpl'
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: team-X-mails
  routes:
    - matchers:
        - service=~"foo1|foo2|baz"
      receiver: team-X-mails
    - matchers:
        - service=~"zookeeper"
      receiver: team-X-slacks
    - matchers:
        - service="database"
      receiver: team-DB-pagers
    - matchers:
        - severity="critical"
      receiver: team-critical-webhooks
- matchers:
        - severity="warning"
        - pod="kafka"
      receiver: team-warning-webhooks
inhibit_rules:
  - source_matchers: [severity="critical"]
    target_matchers: [severity="warning"]
    equal: [alertname, cluster, service]
receivers:
  - name: 'team-X-slacks'
    slack_configs:
      - to: 'team-X+alerts@example.org'
  - name: 'team-X-mails'
    email_configs:
      - to: 'team-X+alerts-critical@example.org'
    pagerduty_configs:
      - service_key: <team-X-key>
  - name: 'team-Y-slacks'
    slack_configs:
      - to: 'team-Y+alerts@example.org'
  - name: 'team-X-pagers'
    pagerduty_configs:
      - service_key: <team-Y-key>
  - name: 'team-DB-pagers'
    pagerduty_configs:
      - service_key: <team-DB-key>
  - name: 'team-critical-webhooks'
    webhook_configs:
      - service_key: <team-DB-key>
- name: 'team-warning-webhooks'
webhook_configs:
- service_key: <team-DB-key>