global:
  smtp_smarthost: 'localhost:25'
  smtp_from: 'alertmanager@example.org'
  smtp_auth_username: 'alertmanager'
  smtp_auth_password: 'password'
templates:
  - '/etc/alertmanager/template/*.tmpl'
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: X-mails
  routes:
    - matchers:
        - service=~"foo1|foo2|baz"
      receiver: X-mails
    - matchers:
        - service="files"
      receiver: Y-mails
    - matchers:
        - service="database"
      receiver: team-DB-pager
    - matchers:
        - severity="critical"
      receiver: team-critical-pager
    - matchers:
        - severity="warning"
      receiver: team-warning-pager
inhibit_rules:
  - source_matchers: [severity="critical"]
    target_matchers: [severity="warning"]
    equal: [alertname, cluster, service]
receivers:
  - name: 'team-X-mails'
    email_configs:
      - to: 'team-X+alerts@example.org'
  - name: 'team-X-pager'
    email_configs:
      - to: 'team-X+alerts-critical@example.org'
    pagerduty_configs:
      - service_key: <team-X-key>
  - name: 'team-Y-mails'
    email_configs:
      - to: 'team-Y+alerts@example.org'
  - name: 'team-Y-pager'
    pagerduty_configs:
      - service_key: <team-Y-key>
  - name: 'team-DB-pager'
    pagerduty_configs:
      - service_key: <team-DB-key>